// <auto-generated />
using System;
using DDDKHostAPI.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDKHostAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220721173923_TestDataAdded")]
    partial class TestDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DDDKHostAPI.Models.Data.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A",
                            PhFactor = "-"
                        },
                        new
                        {
                            Id = 3,
                            Name = "B",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "B",
                            PhFactor = "-"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AB",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AB",
                            PhFactor = "-"
                        },
                        new
                        {
                            Id = 7,
                            Name = "0",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 8,
                            Name = "0",
                            PhFactor = "-"
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonationEventId")
                        .HasColumnType("int");

                    b.Property<int>("DonatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationEventId");

                    b.HasIndex("DonatorId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonationEventId = 1,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 2,
                            DonationEventId = 1,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 3,
                            DonationEventId = 2,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 4,
                            DonationEventId = 1,
                            DonatorId = 2
                        },
                        new
                        {
                            Id = 5,
                            DonationEventId = 2,
                            DonatorId = 2
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.DonationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("DonationEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Akcija dobrovoljnog darovanja krvi u D. Crnjelovu 2021",
                            EventDate = new DateTime(2021, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Akcija dobrovoljnog darovanja krvi u Magnojevicu 2022",
                            EventDate = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BloodTypeId");

                    b.ToTable("Donators");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Dusana Baranina 1/C/10, Bijeljina",
                            BirthDate = new DateTime(1986, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 7,
                            Email = "aleksbn417@gmail.com",
                            FirstName = "Aleksandar",
                            LastName = "Matic",
                            PhoneNumber = "065/417-302"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Vrulja bb, Donje Crnjelovo",
                            BirthDate = new DateTime(1958, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 5,
                            Email = "pperic@gmail.com",
                            FirstName = "Petar",
                            LastName = "Peric",
                            PhoneNumber = "065/257-417"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Gavrila Principa 14/22, Bijeljina",
                            BirthDate = new DateTime(2000, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 5,
                            Email = "ivanas@gmail.com",
                            FirstName = "Ivana",
                            LastName = "Stevic",
                            PhoneNumber = "065/741-956"
                        },
                        new
                        {
                            ID = 4,
                            Address = "Mala Obarska BB",
                            BirthDate = new DateTime(2001, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 6,
                            Email = "majag@gmail.com",
                            FirstName = "Maja",
                            LastName = "Gobeljic",
                            PhoneNumber = "065/778-332"
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Škola u Donjem Crnjelovu",
                            Name = "Donje Crnjelovo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dom omladine",
                            Name = "Magnojević"
                        },
                        new
                        {
                            Id = 3,
                            Description = "OŠ Knez Ivo od Semberije",
                            Name = "Bijeljina - Dašnjica 1"
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donation", b =>
                {
                    b.HasOne("DDDKHostAPI.Models.Data.DonationEvent", "DonationEvent")
                        .WithMany()
                        .HasForeignKey("DonationEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDKHostAPI.Models.Data.Donator", "Donator")
                        .WithMany("Donations")
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationEvent");

                    b.Navigation("Donator");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.DonationEvent", b =>
                {
                    b.HasOne("DDDKHostAPI.Models.Data.Location", "Location")
                        .WithMany("DonationEvents")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donator", b =>
                {
                    b.HasOne("DDDKHostAPI.Models.Data.BloodType", "BloodType")
                        .WithMany("Donators")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.BloodType", b =>
                {
                    b.Navigation("Donators");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donator", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Location", b =>
                {
                    b.Navigation("DonationEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
