// <auto-generated />
using System;
using DDDKHostAPI.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDKHostAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221224155306_DataUpdated")]
    partial class DataUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DDDKHostAPI.Models.Data.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A",
                            PhFactor = "-"
                        },
                        new
                        {
                            Id = 3,
                            Name = "B",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 4,
                            Name = "B",
                            PhFactor = "-"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AB",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AB",
                            PhFactor = "-"
                        },
                        new
                        {
                            Id = 7,
                            Name = "0",
                            PhFactor = "+"
                        },
                        new
                        {
                            Id = 8,
                            Name = "0",
                            PhFactor = "-"
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonationEventId")
                        .HasColumnType("int");

                    b.Property<int>("DonatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationEventId");

                    b.HasIndex("DonatorId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonationEventId = 7,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 2,
                            DonationEventId = 20,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 3,
                            DonationEventId = 16,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 4,
                            DonationEventId = 13,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 5,
                            DonationEventId = 6,
                            DonatorId = 12
                        },
                        new
                        {
                            Id = 6,
                            DonationEventId = 15,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 7,
                            DonationEventId = 10,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 8,
                            DonationEventId = 5,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 9,
                            DonationEventId = 15,
                            DonatorId = 5
                        },
                        new
                        {
                            Id = 10,
                            DonationEventId = 5,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 11,
                            DonationEventId = 11,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 12,
                            DonationEventId = 9,
                            DonatorId = 24
                        },
                        new
                        {
                            Id = 13,
                            DonationEventId = 2,
                            DonatorId = 18
                        },
                        new
                        {
                            Id = 14,
                            DonationEventId = 20,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 15,
                            DonationEventId = 13,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 16,
                            DonationEventId = 17,
                            DonatorId = 13
                        },
                        new
                        {
                            Id = 17,
                            DonationEventId = 5,
                            DonatorId = 2
                        },
                        new
                        {
                            Id = 18,
                            DonationEventId = 20,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 19,
                            DonationEventId = 12,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 20,
                            DonationEventId = 13,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 21,
                            DonationEventId = 14,
                            DonatorId = 14
                        },
                        new
                        {
                            Id = 22,
                            DonationEventId = 1,
                            DonatorId = 8
                        },
                        new
                        {
                            Id = 23,
                            DonationEventId = 16,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 24,
                            DonationEventId = 7,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 25,
                            DonationEventId = 20,
                            DonatorId = 22
                        },
                        new
                        {
                            Id = 26,
                            DonationEventId = 8,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 27,
                            DonationEventId = 1,
                            DonatorId = 20
                        },
                        new
                        {
                            Id = 28,
                            DonationEventId = 10,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 29,
                            DonationEventId = 7,
                            DonatorId = 28
                        },
                        new
                        {
                            Id = 30,
                            DonationEventId = 16,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 31,
                            DonationEventId = 9,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 32,
                            DonationEventId = 18,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 33,
                            DonationEventId = 3,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 34,
                            DonationEventId = 9,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 35,
                            DonationEventId = 3,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 36,
                            DonationEventId = 13,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 37,
                            DonationEventId = 11,
                            DonatorId = 2
                        },
                        new
                        {
                            Id = 38,
                            DonationEventId = 19,
                            DonatorId = 24
                        },
                        new
                        {
                            Id = 39,
                            DonationEventId = 10,
                            DonatorId = 29
                        },
                        new
                        {
                            Id = 40,
                            DonationEventId = 1,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 41,
                            DonationEventId = 3,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 42,
                            DonationEventId = 12,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 43,
                            DonationEventId = 1,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 44,
                            DonationEventId = 7,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 45,
                            DonationEventId = 20,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 46,
                            DonationEventId = 17,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 47,
                            DonationEventId = 9,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 48,
                            DonationEventId = 2,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 49,
                            DonationEventId = 4,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 50,
                            DonationEventId = 10,
                            DonatorId = 6
                        },
                        new
                        {
                            Id = 51,
                            DonationEventId = 20,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 52,
                            DonationEventId = 4,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 53,
                            DonationEventId = 15,
                            DonatorId = 6
                        },
                        new
                        {
                            Id = 54,
                            DonationEventId = 8,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 55,
                            DonationEventId = 10,
                            DonatorId = 28
                        },
                        new
                        {
                            Id = 56,
                            DonationEventId = 18,
                            DonatorId = 5
                        },
                        new
                        {
                            Id = 57,
                            DonationEventId = 1,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 58,
                            DonationEventId = 1,
                            DonatorId = 8
                        },
                        new
                        {
                            Id = 59,
                            DonationEventId = 17,
                            DonatorId = 29
                        },
                        new
                        {
                            Id = 60,
                            DonationEventId = 19,
                            DonatorId = 12
                        },
                        new
                        {
                            Id = 61,
                            DonationEventId = 2,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 62,
                            DonationEventId = 7,
                            DonatorId = 13
                        },
                        new
                        {
                            Id = 63,
                            DonationEventId = 3,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 64,
                            DonationEventId = 16,
                            DonatorId = 8
                        },
                        new
                        {
                            Id = 65,
                            DonationEventId = 14,
                            DonatorId = 20
                        },
                        new
                        {
                            Id = 66,
                            DonationEventId = 19,
                            DonatorId = 13
                        },
                        new
                        {
                            Id = 67,
                            DonationEventId = 4,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 68,
                            DonationEventId = 2,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 69,
                            DonationEventId = 8,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 70,
                            DonationEventId = 16,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 71,
                            DonationEventId = 9,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 72,
                            DonationEventId = 6,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 73,
                            DonationEventId = 8,
                            DonatorId = 27
                        },
                        new
                        {
                            Id = 74,
                            DonationEventId = 18,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 75,
                            DonationEventId = 20,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 76,
                            DonationEventId = 16,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 77,
                            DonationEventId = 12,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 78,
                            DonationEventId = 3,
                            DonatorId = 22
                        },
                        new
                        {
                            Id = 79,
                            DonationEventId = 6,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 80,
                            DonationEventId = 12,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 81,
                            DonationEventId = 4,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 82,
                            DonationEventId = 8,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 83,
                            DonationEventId = 11,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 84,
                            DonationEventId = 18,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 85,
                            DonationEventId = 10,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 86,
                            DonationEventId = 3,
                            DonatorId = 24
                        },
                        new
                        {
                            Id = 87,
                            DonationEventId = 5,
                            DonatorId = 6
                        },
                        new
                        {
                            Id = 88,
                            DonationEventId = 15,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 89,
                            DonationEventId = 5,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 90,
                            DonationEventId = 15,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 91,
                            DonationEventId = 3,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 92,
                            DonationEventId = 11,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 93,
                            DonationEventId = 4,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 94,
                            DonationEventId = 1,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 95,
                            DonationEventId = 4,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 96,
                            DonationEventId = 11,
                            DonatorId = 27
                        },
                        new
                        {
                            Id = 97,
                            DonationEventId = 19,
                            DonatorId = 12
                        },
                        new
                        {
                            Id = 98,
                            DonationEventId = 14,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 99,
                            DonationEventId = 3,
                            DonatorId = 2
                        },
                        new
                        {
                            Id = 100,
                            DonationEventId = 2,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 101,
                            DonationEventId = 10,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 102,
                            DonationEventId = 2,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 103,
                            DonationEventId = 10,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 104,
                            DonationEventId = 7,
                            DonatorId = 8
                        },
                        new
                        {
                            Id = 105,
                            DonationEventId = 11,
                            DonatorId = 27
                        },
                        new
                        {
                            Id = 106,
                            DonationEventId = 11,
                            DonatorId = 22
                        },
                        new
                        {
                            Id = 107,
                            DonationEventId = 14,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 108,
                            DonationEventId = 12,
                            DonatorId = 22
                        },
                        new
                        {
                            Id = 109,
                            DonationEventId = 4,
                            DonatorId = 8
                        },
                        new
                        {
                            Id = 110,
                            DonationEventId = 1,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 111,
                            DonationEventId = 17,
                            DonatorId = 8
                        },
                        new
                        {
                            Id = 112,
                            DonationEventId = 16,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 113,
                            DonationEventId = 9,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 114,
                            DonationEventId = 2,
                            DonatorId = 27
                        },
                        new
                        {
                            Id = 115,
                            DonationEventId = 8,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 116,
                            DonationEventId = 4,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 117,
                            DonationEventId = 3,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 118,
                            DonationEventId = 10,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 119,
                            DonationEventId = 3,
                            DonatorId = 13
                        },
                        new
                        {
                            Id = 120,
                            DonationEventId = 11,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 121,
                            DonationEventId = 4,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 122,
                            DonationEventId = 19,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 123,
                            DonationEventId = 18,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 124,
                            DonationEventId = 4,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 125,
                            DonationEventId = 2,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 126,
                            DonationEventId = 20,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 127,
                            DonationEventId = 9,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 128,
                            DonationEventId = 3,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 129,
                            DonationEventId = 17,
                            DonatorId = 28
                        },
                        new
                        {
                            Id = 130,
                            DonationEventId = 17,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 131,
                            DonationEventId = 6,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 132,
                            DonationEventId = 12,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 133,
                            DonationEventId = 2,
                            DonatorId = 24
                        },
                        new
                        {
                            Id = 134,
                            DonationEventId = 19,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 135,
                            DonationEventId = 1,
                            DonatorId = 9
                        },
                        new
                        {
                            Id = 136,
                            DonationEventId = 12,
                            DonatorId = 12
                        },
                        new
                        {
                            Id = 137,
                            DonationEventId = 11,
                            DonatorId = 13
                        },
                        new
                        {
                            Id = 138,
                            DonationEventId = 19,
                            DonatorId = 5
                        },
                        new
                        {
                            Id = 139,
                            DonationEventId = 11,
                            DonatorId = 6
                        },
                        new
                        {
                            Id = 140,
                            DonationEventId = 18,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 141,
                            DonationEventId = 17,
                            DonatorId = 14
                        },
                        new
                        {
                            Id = 142,
                            DonationEventId = 3,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 143,
                            DonationEventId = 14,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 144,
                            DonationEventId = 11,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 145,
                            DonationEventId = 7,
                            DonatorId = 6
                        },
                        new
                        {
                            Id = 146,
                            DonationEventId = 14,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 147,
                            DonationEventId = 13,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 148,
                            DonationEventId = 14,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 149,
                            DonationEventId = 15,
                            DonatorId = 5
                        },
                        new
                        {
                            Id = 150,
                            DonationEventId = 6,
                            DonatorId = 2
                        },
                        new
                        {
                            Id = 151,
                            DonationEventId = 1,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 152,
                            DonationEventId = 19,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 153,
                            DonationEventId = 11,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 154,
                            DonationEventId = 19,
                            DonatorId = 14
                        },
                        new
                        {
                            Id = 155,
                            DonationEventId = 19,
                            DonatorId = 12
                        },
                        new
                        {
                            Id = 156,
                            DonationEventId = 14,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 157,
                            DonationEventId = 20,
                            DonatorId = 18
                        },
                        new
                        {
                            Id = 158,
                            DonationEventId = 2,
                            DonatorId = 22
                        },
                        new
                        {
                            Id = 159,
                            DonationEventId = 10,
                            DonatorId = 1
                        },
                        new
                        {
                            Id = 160,
                            DonationEventId = 10,
                            DonatorId = 16
                        },
                        new
                        {
                            Id = 161,
                            DonationEventId = 12,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 162,
                            DonationEventId = 5,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 163,
                            DonationEventId = 18,
                            DonatorId = 5
                        },
                        new
                        {
                            Id = 164,
                            DonationEventId = 18,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 165,
                            DonationEventId = 1,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 166,
                            DonationEventId = 14,
                            DonatorId = 27
                        },
                        new
                        {
                            Id = 167,
                            DonationEventId = 1,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 168,
                            DonationEventId = 2,
                            DonatorId = 21
                        },
                        new
                        {
                            Id = 169,
                            DonationEventId = 9,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 170,
                            DonationEventId = 16,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 171,
                            DonationEventId = 10,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 172,
                            DonationEventId = 11,
                            DonatorId = 20
                        },
                        new
                        {
                            Id = 173,
                            DonationEventId = 4,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 174,
                            DonationEventId = 15,
                            DonatorId = 10
                        },
                        new
                        {
                            Id = 175,
                            DonationEventId = 17,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 176,
                            DonationEventId = 10,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 177,
                            DonationEventId = 8,
                            DonatorId = 2
                        },
                        new
                        {
                            Id = 178,
                            DonationEventId = 12,
                            DonatorId = 13
                        },
                        new
                        {
                            Id = 179,
                            DonationEventId = 16,
                            DonatorId = 23
                        },
                        new
                        {
                            Id = 180,
                            DonationEventId = 1,
                            DonatorId = 18
                        },
                        new
                        {
                            Id = 181,
                            DonationEventId = 2,
                            DonatorId = 4
                        },
                        new
                        {
                            Id = 182,
                            DonationEventId = 19,
                            DonatorId = 18
                        },
                        new
                        {
                            Id = 183,
                            DonationEventId = 8,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 184,
                            DonationEventId = 3,
                            DonatorId = 26
                        },
                        new
                        {
                            Id = 185,
                            DonationEventId = 15,
                            DonatorId = 20
                        },
                        new
                        {
                            Id = 186,
                            DonationEventId = 14,
                            DonatorId = 30
                        },
                        new
                        {
                            Id = 187,
                            DonationEventId = 12,
                            DonatorId = 28
                        },
                        new
                        {
                            Id = 188,
                            DonationEventId = 9,
                            DonatorId = 15
                        },
                        new
                        {
                            Id = 189,
                            DonationEventId = 16,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 190,
                            DonationEventId = 8,
                            DonatorId = 20
                        },
                        new
                        {
                            Id = 191,
                            DonationEventId = 1,
                            DonatorId = 11
                        },
                        new
                        {
                            Id = 192,
                            DonationEventId = 15,
                            DonatorId = 7
                        },
                        new
                        {
                            Id = 193,
                            DonationEventId = 7,
                            DonatorId = 3
                        },
                        new
                        {
                            Id = 194,
                            DonationEventId = 5,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 195,
                            DonationEventId = 14,
                            DonatorId = 25
                        },
                        new
                        {
                            Id = 196,
                            DonationEventId = 19,
                            DonatorId = 17
                        },
                        new
                        {
                            Id = 197,
                            DonationEventId = 17,
                            DonatorId = 19
                        },
                        new
                        {
                            Id = 198,
                            DonationEventId = 10,
                            DonatorId = 29
                        },
                        new
                        {
                            Id = 199,
                            DonationEventId = 9,
                            DonatorId = 22
                        },
                        new
                        {
                            Id = 200,
                            DonationEventId = 9,
                            DonatorId = 13
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.DonationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("DonationEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 0",
                            EventDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 8
                        },
                        new
                        {
                            Id = 2,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 1",
                            EventDate = new DateTime(2016, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 2",
                            EventDate = new DateTime(2019, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 3",
                            EventDate = new DateTime(2018, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 4",
                            EventDate = new DateTime(2018, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 10
                        },
                        new
                        {
                            Id = 6,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 5",
                            EventDate = new DateTime(2015, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4
                        },
                        new
                        {
                            Id = 7,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 6",
                            EventDate = new DateTime(2017, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 9
                        },
                        new
                        {
                            Id = 8,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 7",
                            EventDate = new DateTime(2015, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 8",
                            EventDate = new DateTime(2017, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 9",
                            EventDate = new DateTime(2015, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 8
                        },
                        new
                        {
                            Id = 11,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 10",
                            EventDate = new DateTime(2017, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 11",
                            EventDate = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 10
                        },
                        new
                        {
                            Id = 13,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 12",
                            EventDate = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 13",
                            EventDate = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 14",
                            EventDate = new DateTime(2021, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 10
                        },
                        new
                        {
                            Id = 16,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 15",
                            EventDate = new DateTime(2015, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 6
                        },
                        new
                        {
                            Id = 17,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 16",
                            EventDate = new DateTime(2017, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 9
                        },
                        new
                        {
                            Id = 18,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 17",
                            EventDate = new DateTime(2019, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 18",
                            EventDate = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Akcija dobrovoljnog darovanja krvi br. 19",
                            EventDate = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 7
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreviousDonations")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BloodTypeId");

                    b.ToTable("Donators");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Dusana Baranina 86",
                            BirthDate = new DateTime(1987, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 5,
                            Email = "DejanLalic1921000009@gmail.com",
                            FirstName = "Dejan",
                            LastName = "Lalic",
                            PhoneNumber = "065/421-839",
                            PreviousDonations = 18
                        },
                        new
                        {
                            ID = 2,
                            Address = "Sime Matavulja 2",
                            BirthDate = new DateTime(1950, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "DejanIvkovic1407598415@gmail.com",
                            FirstName = "Dejan",
                            LastName = "Ivkovic",
                            PhoneNumber = "065/768-700",
                            PreviousDonations = 10
                        },
                        new
                        {
                            ID = 3,
                            Address = "Kralja Petra I Karadjordjevica 30",
                            BirthDate = new DateTime(1958, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 7,
                            Email = "MitarBecic501237232@gmail.com",
                            FirstName = "Mitar",
                            LastName = "Becic",
                            PhoneNumber = "065/595-961",
                            PreviousDonations = 10
                        },
                        new
                        {
                            ID = 4,
                            Address = "Kralja Petra I Karadjordjevica 125",
                            BirthDate = new DateTime(1976, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 6,
                            Email = "JovanaStevanovic653417260@gmail.com",
                            FirstName = "Jovana",
                            LastName = "Stevanovic",
                            PhoneNumber = "065/113-650",
                            PreviousDonations = 14
                        },
                        new
                        {
                            ID = 5,
                            Address = "Svetozara Markovica 181",
                            BirthDate = new DateTime(1981, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "DejanTadic1596002669@gmail.com",
                            FirstName = "Dejan",
                            LastName = "Tadic",
                            PhoneNumber = "065/562-625",
                            PreviousDonations = 19
                        },
                        new
                        {
                            ID = 6,
                            Address = "Danila Kisa 22",
                            BirthDate = new DateTime(1999, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 7,
                            Email = "IvanaTanaskovic166879211@gmail.com",
                            FirstName = "Ivana",
                            LastName = "Tanaskovic",
                            PhoneNumber = "065/740-342",
                            PreviousDonations = 16
                        },
                        new
                        {
                            ID = 7,
                            Address = "Dusana Silnog 131",
                            BirthDate = new DateTime(1993, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 7,
                            Email = "IvanDjordjevic1822315695@gmail.com",
                            FirstName = "Ivan",
                            LastName = "Djordjevic",
                            PhoneNumber = "065/966-769",
                            PreviousDonations = 7
                        },
                        new
                        {
                            ID = 8,
                            Address = "Dinastije Obrenovic 73",
                            BirthDate = new DateTime(1964, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 2,
                            Email = "NikolinaDjordjevic792331423@gmail.com",
                            FirstName = "Nikolina",
                            LastName = "Djordjevic",
                            PhoneNumber = "065/848-276",
                            PreviousDonations = 18
                        },
                        new
                        {
                            ID = 9,
                            Address = "Dusana Silnog 78",
                            BirthDate = new DateTime(1968, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 8,
                            Email = "AleksandraStojkovic1326566077@gmail.com",
                            FirstName = "Aleksandra",
                            LastName = "Stojkovic",
                            PhoneNumber = "065/764-579",
                            PreviousDonations = 11
                        },
                        new
                        {
                            ID = 10,
                            Address = "Dinastije Obrenovic 104",
                            BirthDate = new DateTime(1970, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 2,
                            Email = "NevenTanaskovic26767992@gmail.com",
                            FirstName = "Neven",
                            LastName = "Tanaskovic",
                            PhoneNumber = "065/425-133",
                            PreviousDonations = 3
                        },
                        new
                        {
                            ID = 11,
                            Address = "Kralja Petra I Karadjordjevica 180",
                            BirthDate = new DateTime(1953, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "DejanLalic1185025398@gmail.com",
                            FirstName = "Dejan",
                            LastName = "Lalic",
                            PhoneNumber = "065/179-619",
                            PreviousDonations = 16
                        },
                        new
                        {
                            ID = 12,
                            Address = "Patrijarha Pavla 57",
                            BirthDate = new DateTime(1955, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "NikolinaAleksic1211252397@gmail.com",
                            FirstName = "Nikolina",
                            LastName = "Aleksic",
                            PhoneNumber = "065/376-735",
                            PreviousDonations = 17
                        },
                        new
                        {
                            ID = 13,
                            Address = "Jovana Ducica 27",
                            BirthDate = new DateTime(1963, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "ZeljkaStevic98602067@gmail.com",
                            FirstName = "Zeljka",
                            LastName = "Stevic",
                            PhoneNumber = "065/924-240",
                            PreviousDonations = 11
                        },
                        new
                        {
                            ID = 14,
                            Address = "Mihajla Pupina 100",
                            BirthDate = new DateTime(1989, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 5,
                            Email = "IvanaLalic1284667572@gmail.com",
                            FirstName = "Ivana",
                            LastName = "Lalic",
                            PhoneNumber = "065/142-630",
                            PreviousDonations = 14
                        },
                        new
                        {
                            ID = 15,
                            Address = "Dusana Silnog 58",
                            BirthDate = new DateTime(1990, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 3,
                            Email = "MirkoBojic101560506@gmail.com",
                            FirstName = "Mirko",
                            LastName = "Bojic",
                            PhoneNumber = "065/390-193",
                            PreviousDonations = 8
                        },
                        new
                        {
                            ID = 16,
                            Address = "Dusana Baranina 161",
                            BirthDate = new DateTime(1995, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 8,
                            Email = "MarijaTanaskovic1756391511@gmail.com",
                            FirstName = "Marija",
                            LastName = "Tanaskovic",
                            PhoneNumber = "065/525-340",
                            PreviousDonations = 8
                        },
                        new
                        {
                            ID = 17,
                            Address = "Svetozara Markovica 112",
                            BirthDate = new DateTime(1987, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "NikolinaJokanovic1442604654@gmail.com",
                            FirstName = "Nikolina",
                            LastName = "Jokanovic",
                            PhoneNumber = "065/788-966",
                            PreviousDonations = 6
                        },
                        new
                        {
                            ID = 18,
                            Address = "Mihajla Pupina 167",
                            BirthDate = new DateTime(1994, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 5,
                            Email = "AleksandarStojkovic487589247@gmail.com",
                            FirstName = "Aleksandar",
                            LastName = "Stojkovic",
                            PhoneNumber = "065/934-931",
                            PreviousDonations = 12
                        },
                        new
                        {
                            ID = 19,
                            Address = "Svetozara Markovica 199",
                            BirthDate = new DateTime(1976, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "SandraPetrovic328810608@gmail.com",
                            FirstName = "Sandra",
                            LastName = "Petrovic",
                            PhoneNumber = "065/824-335",
                            PreviousDonations = 15
                        },
                        new
                        {
                            ID = 20,
                            Address = "Dusana Baranina 12",
                            BirthDate = new DateTime(1962, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 3,
                            Email = "MitarMarkovic1632380195@gmail.com",
                            FirstName = "Mitar",
                            LastName = "Markovic",
                            PhoneNumber = "065/205-414",
                            PreviousDonations = 10
                        },
                        new
                        {
                            ID = 21,
                            Address = "Nikole Tesle 111",
                            BirthDate = new DateTime(1979, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 5,
                            Email = "MitarBecic1264220816@gmail.com",
                            FirstName = "Mitar",
                            LastName = "Becic",
                            PhoneNumber = "065/888-925",
                            PreviousDonations = 2
                        },
                        new
                        {
                            ID = 22,
                            Address = "Dusana Baranina 183",
                            BirthDate = new DateTime(1992, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 6,
                            Email = "AleksandraPopovic355859244@gmail.com",
                            FirstName = "Aleksandra",
                            LastName = "Popovic",
                            PhoneNumber = "065/342-246",
                            PreviousDonations = 14
                        },
                        new
                        {
                            ID = 23,
                            Address = "Ive Andrica 175",
                            BirthDate = new DateTime(1999, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "IvanJokanovic947332160@gmail.com",
                            FirstName = "Ivan",
                            LastName = "Jokanovic",
                            PhoneNumber = "065/288-399",
                            PreviousDonations = 19
                        },
                        new
                        {
                            ID = 24,
                            Address = "Nikole Tesle 199",
                            BirthDate = new DateTime(1962, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "BojanMarkovic1384154158@gmail.com",
                            FirstName = "Bojan",
                            LastName = "Markovic",
                            PhoneNumber = "065/516-744",
                            PreviousDonations = 3
                        },
                        new
                        {
                            ID = 25,
                            Address = "Dusana Silnog 37",
                            BirthDate = new DateTime(1971, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 8,
                            Email = "MitarJovic816575905@gmail.com",
                            FirstName = "Mitar",
                            LastName = "Jovic",
                            PhoneNumber = "065/176-663",
                            PreviousDonations = 18
                        },
                        new
                        {
                            ID = 26,
                            Address = "Petra Kocica 177",
                            BirthDate = new DateTime(1968, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 1,
                            Email = "SlavkoStevic1111217866@gmail.com",
                            FirstName = "Slavko",
                            LastName = "Stevic",
                            PhoneNumber = "065/976-267",
                            PreviousDonations = 14
                        },
                        new
                        {
                            ID = 27,
                            Address = "Svetog Save 37",
                            BirthDate = new DateTime(1954, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 6,
                            Email = "UrosIvkovic1553616651@gmail.com",
                            FirstName = "Uros",
                            LastName = "Ivkovic",
                            PhoneNumber = "065/318-439",
                            PreviousDonations = 2
                        },
                        new
                        {
                            ID = 28,
                            Address = "Patrijarha Pavla 39",
                            BirthDate = new DateTime(1953, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 7,
                            Email = "IvanTanaskovic1882093608@gmail.com",
                            FirstName = "Ivan",
                            LastName = "Tanaskovic",
                            PhoneNumber = "065/463-366",
                            PreviousDonations = 15
                        },
                        new
                        {
                            ID = 29,
                            Address = "Petra Kocica 193",
                            BirthDate = new DateTime(1957, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 8,
                            Email = "NevenaStevic1459169646@gmail.com",
                            FirstName = "Nevena",
                            LastName = "Stevic",
                            PhoneNumber = "065/962-550",
                            PreviousDonations = 20
                        },
                        new
                        {
                            ID = 30,
                            Address = "Masarikova 85",
                            BirthDate = new DateTime(1988, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodTypeId = 8,
                            Email = "NevenIvkovic1058554250@gmail.com",
                            FirstName = "Neven",
                            LastName = "Ivkovic",
                            PhoneNumber = "065/887-739",
                            PreviousDonations = 19
                        });
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Škola u Donjem Crnjelovu",
                            Name = "Donje Crnjelovo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dom omladine",
                            Name = "Magnojević"
                        },
                        new
                        {
                            Id = 3,
                            Description = "OŠ Knez Ivo od Semberije",
                            Name = "Bijeljina - Dašnjica 1"
                        },
                        new
                        {
                            Id = 4,
                            Description = "OŠ Vuk Karadžić",
                            Name = "Bijeljina - Vuk Karadzic skola"
                        },
                        new
                        {
                            Id = 5,
                            Description = "OŠ Sveti Sava",
                            Name = "Dvorovi - škola"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dom Omladine Velika Obarska",
                            Name = "Velika Obarska"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sala Osnovne škole",
                            Name = "Batković"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ambulanta Branjevo",
                            Name = "Branjevo"
                        },
                        new
                        {
                            Id = 9,
                            Description = "OŠ Jovan Dučić Patkovača",
                            Name = "Patkovača"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Banja Dvorovi",
                            Name = "Dvorovi - Banja"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "815b0251-1b6b-4a2c-ae26-996d7f69f9ee",
                            ConcurrencyStamp = "c4292a59-46f4-431b-9957-91ad89a2bb94",
                            Name = "Admin",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "5e950671-8968-413a-8c2c-4a025794a673",
                            ConcurrencyStamp = "819fa164-8357-4935-97c5-ad1192b3e149",
                            Name = "Mod",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donation", b =>
                {
                    b.HasOne("DDDKHostAPI.Models.Data.DonationEvent", "DonationEvent")
                        .WithMany()
                        .HasForeignKey("DonationEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDKHostAPI.Models.Data.Donator", "Donator")
                        .WithMany("Donations")
                        .HasForeignKey("DonatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonationEvent");

                    b.Navigation("Donator");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.DonationEvent", b =>
                {
                    b.HasOne("DDDKHostAPI.Models.Data.Location", "Location")
                        .WithMany("DonationEvents")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donator", b =>
                {
                    b.HasOne("DDDKHostAPI.Models.Data.BloodType", "BloodType")
                        .WithMany("Donators")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.BloodType", b =>
                {
                    b.Navigation("Donators");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Donator", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("DDDKHostAPI.Models.Data.Location", b =>
                {
                    b.Navigation("DonationEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
